spring:
  sql:
    init:
      data:
  application:
    name: AdventureWorks_api
  mustache:
    suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5050/adventureworks_db
    username: postgres
    password: feliequipo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true